### ISSUE TITLE
Can you compare this benchmark tool with wrk and alike?

### ISSUE THREAD

**Issue by hiradyazdan** [socketry/benchmark-http#1]
Hi, Can you compare your benchmark tool with wrk or similar tools like below?

https://github.com/denji/awesome-http-benchmark

I am quite interested in the concurrency benchmark, and thought also the machine which is doing the benchmark could also affect the result, but wanted to confirm and see how this could be accurate in comparison with other tools specially wrk?

**Comment by ioquatix** [comment]
`benchmark-http` evaluates how latency changes as the number of simultaneous requests is increased. If you run it over a high latency link vs a low latency link you will get different results.

`wrk` is more concerned with raw throughput. It’s a little bit more efficient in this regard. It also only supports HTTP/1 - you can manually change concurrency level.

I wasn’t so interested in trying to remake `wrk` but to try and find more meaningful numbers automatically.

**Comment by ioquatix** [comment]
The link you give is pretty awesome, maybe you can submit a PR with a "See Also" section and a link to that repo/page.

**Comment by hiradyazdan** [comment]
Hi, Sorry I was traveling and couldn't reply back. 

I was referring to `wrk` because of the measurement done in [falcon issue #23](https://github.com/socketry/falcon/issues/23#issuecomment-431968131), and wanted to know the accuracy of that measurement in comparison with your benchmark tool, although i think it is by throughput as you say, rather than concurrency. 

Also, I think `wrk` added new features to manually amend the benchmark to do concurrency benchmark as well.

The reason I am quite interested in benchmark tools like yours, is that I am at stage where I need to decide whether to integrate `falcon` and replace `puma` for a project of mine which requires high performance for Rails `HTTP/1` and `HTTP/2` requests (despite the fact that `Rails` itself has a lot of features which overall add to the performance hit), or try to somehow use the `puma early hints` and leave the `h2` calls to an `nginx` server. But that's another story belongs to a different repository.

Thanks for your explanation and I am looking forward to see your progress on this tool and also `falcon` which seems quite a decent replacement for `puma`.

**Comment by ioquatix** [comment]
I did a screen cast that might be of interest to you https://youtu.be/2u6JRvKh7Dg
